### ISSUE TITLE
[BUG]: Compile error "constexpr variable cannot have non-literal type" in parse_freq_string.hpp

### ISSUE THREAD

**Issue by gitterdude** [ZL-Audio/ZLEqualizer#225]
### Thanks for taking the time to fill out this bug report!

- [x] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
I'm trying to compile 0.6.2 from git, following the "Clone and Build" instructions in README.md, and I'm getting the error 

ZLEqualizer/source/panel/control_panel/left_control_panel/../../helper/helper.hpp:14:
ZLEqualizer/source/panel/control_panel/left_control_panel/../../helper/parse_freq_string.hpp:15:50: error: constexpr variable cannot have non-literal type 'const std::array<std::string, 12>' (aka 'const array<basic_string<char>, 12>')
   15 |     static constexpr std::array<std::string, 12> pitchLookUp{
      |                                                  ^

I've tried both llvm 17.0.5, 20.1.6 and gcc 11.4.0.

I've bisected it to commit 17ccc9ad9320
```

### Additional information

```markdown
- Operating system (& version if applicable): Ubuntu 22.04
- Hardware (CPU & GPU if applicable): Intel(R) Core(TM) i7-3770
- DAW:
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow the Code of Conduct.
